eShopWorld/captain-hook

src/CaptainHook.PoolManagerActor/CaptainHook.PoolManagerActor.csproj
src/CaptainHook.PoolManagerActor/PoolManagerActor.cs
src/Tests/CaptainHook.Tests/Actors/PoolManagerActorTests.cs
src/Tests/CaptainHook.Tests/CaptainHook.Tests.csproj

* Fixing some bugs in the pool manger flow
* Added some actor tests
* Changed event name

Bug fix and pool manger tests

---

src/CaptainHook.Common/Authentication/AuthenticationConfig.cs
src/CaptainHook.EventHandlerActor/Program.cs
src/CaptainHook.EventReaderActor/EventReaderActor.cs
src/Tests/CaptainHook.Tests/Authentication/ContentTypeExtensions.cs

* Update timer to actor timer.
* Small refactor to remove unused references

Changing timer to actor timer

---

src/CaptainHook.Common/CaptainHook.Common.csproj
src/CaptainHook.EndpointDispatcherActor/CaptainHook.EndpointDispatcherActor.csproj
src/CaptainHook.EventHandlerActor/CaptainHook.EventHandlerActor.csproj
src/CaptainHook.EventReaderActor/CaptainHook.EventReaderActor.csproj
src/CaptainHook.Fabric/ApplicationPackageRoot/ApplicationManifest.xml
src/CaptainHook.Fabric/ApplicationParameters/CI.xml
src/CaptainHook.Fabric/ApplicationParameters/Local.1Node.xml
src/CaptainHook.Fabric/ApplicationParameters/Local.5Node.xml
src/CaptainHook.Fabric/ApplicationParameters/PREP.xml
src/CaptainHook.Fabric/ApplicationParameters/PROD.xml
src/CaptainHook.Fabric/ApplicationParameters/SAND.xml
src/CaptainHook.Fabric/ApplicationParameters/TEST.xml
src/CaptainHook.Fabric/CaptainHook.Fabric.sfproj
src/CaptainHook.Fabric/packages.config
src/CaptainHook.Interfaces/CaptainHook.Interfaces.csproj
src/CaptainHook.MessagingDirector/CaptainHook.MessagingDirector.csproj
src/CaptainHook.PoolManagerActor/CaptainHook.PoolManagerActor.csproj
src/Tests/CaptainHook.Tests/CaptainHook.Tests.csproj

Nuget updates for CH after telemetry update to fix ToExceptionEvent Parameters.

Nuget updates

---

src/CaptainHook.Common/Exceptions/ClientTokenFailureException.cs
src/CaptainHook.Common/ModelParser.cs
src/CaptainHook.EventHandlerActor/EventHandlerActor.cs
src/CaptainHook.EventHandlerActor/Handlers/Authentication/AuthenticationHandler.cs
src/CaptainHook.Interfaces/IPoolManagerActor.cs
src/CaptainHook.PoolManagerActor/PoolManagerActor.cs
src/Tests/CaptainHook.Tests/Actors/PoolManagerActorTests.cs

fixed issues on message failure unhandled exception path.

Adding more token logging

---

src/CaptainHook.Common/Constants.cs
src/CaptainHook.Common/MessageData.cs
src/CaptainHook.EventHandlerActor/Handlers/GenericWebhookHandler.cs
src/CaptainHook.EventHandlerActor/Handlers/IRequestBuilder.cs
src/CaptainHook.EventHandlerActor/Handlers/RequestBuilder.cs
src/CaptainHook.EventReaderService/EventReaderService.cs
src/CaptainHook.Fabric/ApplicationParameters/Local.1Node.xml
src/Tests/CaptainHook.Tests/Configuration/RequestBuilderTests.cs
src/Tests/CaptainHook.Tests/EventHandlerTestHelper.cs
src/Tests/CaptainHook.Tests/Web/WebHooks/GenericWebHookHandlerVerbTests.cs

added code and tests for new idempotency key header derived off  SB message Id
not sent for GET requests

Add support for Idempotency-Key header

---

src/CaptainHook.Database/Bootstrap.cs
src/CaptainHook.Database/CaptainHook.Database.csproj
src/CaptainHook.Database/CosmosDB/CosmosDbClientFactory.cs
src/CaptainHook.Database/CosmosDB/CosmosDbConfiguration.cs
src/CaptainHook.Database/CosmosDB/CosmosDbRepository.cs
src/CaptainHook.Database/CosmosDB/DocumentContainer.cs
src/CaptainHook.Database/CosmosDB/ICosmosDbClientFactory.cs
src/CaptainHook.Database/CosmosDB/ICosmosDbRepository.cs
src/CaptainHook.Database/CosmosDB/MissingDocumentException.cs
src/CaptainHook.Database/CosmosDB/QueryDefinition.cs
src/CaptainHook.Database/CosmosDB/StaleDataException.cs
src/CaptainHook.Database/Setup/CosmosDbConfigurationException.cs
src/CaptainHook.Database/Setup/DbSettingsParser.cs
src/CaptainHook.DirectorService/CaptainHook.DirectorService.csproj
src/CaptainHook.sln

Introduction of a project, which is going to be moved to a separate package later, that is going to take care of CosmosDB communication for us.
Captain Hook is going to start relying on CosmosDB shortly and we need this capability.
The usage of this code is going to come in the following PRs.

#57443 - introduce CosmosDB communication project

---

src/Tests/CaptainHook.Tests/Web/FlowTests/E2EFlowTestsFixture.cs
src/Tests/CaptainHook.Tests/Web/FlowTests/FlowIntegrationTests.cs
src/Tests/CaptainHook.Tests/Web/FlowTests/IntegrationTestBase.cs
src/Tests/CaptainHook.Tests/Web/FlowTests/PeterPanConsts.cs
src/global.json

unblock test parallelization as original code was not running under xunit scheduling and was hanging on system with less cores

improves code, more test diagnostics

---

src/CaptainHook.Common/CaptainHook.Common.csproj
src/CaptainHook.Common/ServiceModels/EventReaderInitData.cs
src/CaptainHook.DirectorService/DirectorService.cs
src/CaptainHook.EventReaderService/EventReaderService.cs
src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderInitDataTests.cs
src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderTests.cs

Change EventReaderInitData and pass domain configuration from Director to Reader.

#64306 pass event data from director to reader

---

src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
src/CaptainHook.EventHandlerActor/Handlers/WebhookResponseHandler.cs

Referes to these for the logic I've used
- https://github.com/eShopWorld/captain-hook/pull/44/files#r382044213
- https://github.com/eShopWorld/captain-hook/pull/44/files

#68804 fix event logging for failed delivery

---

src/CaptainHook.DirectorService/DirectorService.cs

Due to a merge overlook, the build is currently broken. This PR addresses this issue.

Fixes a broken build.

---

src/CaptainHook.EventHandlerActor/Handlers/RequestBuilder.cs

extra logging is not needed anymore

#69844 remove additional logging

---

src/CaptainHook.EventReaderService/EventReaderService.cs
src/CaptainHook.EventReaderService/HeartBeat/HeartBeatStats.cs
src/CaptainHook.EventReaderService/HeartBeat/ReaderHeartBeatEvent.cs
src/Tests/CaptainHook.Tests/Services/Reliable/HeartBeat/HeartBeatStatsTests.cs

Add additional metrics to monitor delivered and undelivered messages between heartbeats

#72356 - message delivery counter for reader heart beat

---

src/CaptainHook.Domain/Entities/EventEntity.cs
src/CaptainHook.Domain/Entities/WebhooksEntity.cs

Small change to fix the build on the configuration merger tests failing with a "collection was of a fixed size" error.

Fix configuration merger tests

---

src/CaptainHook.Api/Controllers/SubscribersController.cs

quick fix as for now, unit tests in progress

Fix for clearing callback passwords

---

src/CaptainHook.Api/PackageRoot/ServiceManifest.xml
src/CaptainHook.Api/Startup.cs
src/CaptainHook.Fabric/ApplicationPackageRoot/ApplicationManifest.xml

AI logging for CH API was not properly configured. This PR rectifies that.

Add AI logging for API

---

src/CaptainHook.Common/Configuration/Configuration.cs
src/CaptainHook.Common/Configuration/ConfigurationLoader.cs
src/CaptainHook.DirectorService/DirectorService.cs
src/CaptainHook.DirectorService/Infrastructure/Interfaces/ISubscriberConfigurationLoader.cs
src/CaptainHook.DirectorService/Infrastructure/SubscriberConfigurationLoader.cs
src/Tests/CaptainHook.Tests/Configuration/ConfigLoaderTests.cs
src/Tests/CaptainHook.Tests/Director/SubscriberConfigurationLoaderTests.cs
src/Tests/CaptainHook.Tests/TestConstants.cs

Simple change which allows to execute all CaptainHook.Tests tests locally. 
Fixed tests are marked with `IsDev`, so won't fail on environments.

68215 fix KV loading tests

---

src/CaptainHook.Common/Telemetry/FailedWebHookEvent.cs
src/CaptainHook.Common/Telemetry/Web/HttpClientFailure.cs
src/CaptainHook.Common/Telemetry/Web/WebhookEvent.cs
src/CaptainHook.EventHandlerActor/Handlers/GenericWebhookHandler.cs
src/CaptainHook.EventHandlerActor/Handlers/IRequestLogger.cs
src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
src/CaptainHook.EventHandlerActor/Handlers/WebhookResponseHandler.cs
src/Tests/CaptainHook.Tests/Web/WebHooks/GenericWebhookHandlerTests.cs

Added logging to verify why sometimes payload sent to the URI is incorrect.

#75429 - added extra logging and unit test for failing case

---

src/CaptainHook.EventHandlerActor/Handlers/Requests/BuildUriContext.cs
src/CaptainHook.EventHandlerActor/Handlers/Requests/DefaultRequestBuilder.cs
src/CaptainHook.EventHandlerActor/Handlers/Requests/RouteAndReplaceRequestBuilder.cs
src/Tests/CaptainHook.Tests/Configuration/RequestBuilderTests.cs
src/Tests/CaptainHook.Tests/Services/Actors/Requests/RouteAndReplaceRequestBuilderTests.cs

Implement the logic for Route and Replace and test with unit tests
Some comments in the code (especially around exceptions and validation) are going to be addressed in a separate task which is going to address the validation aspect.

Task 75635 route and replace logic implementation

---

src/Tests/CaptainHook.Tests/Builders/SourceParserLocationBuilder.cs
src/Tests/CaptainHook.Tests/Builders/WebhookConfigBuilder.cs
src/Tests/CaptainHook.Tests/Builders/WebhookConfigRouteBuilder.cs
src/Tests/CaptainHook.Tests/Builders/WebhookRequestRuleBuilder.cs
src/Tests/CaptainHook.Tests/Configuration/RequestBuilderTests.cs
src/Tests/CaptainHook.Tests/Services/Actors/Requests/RouteAndReplaceRequestBuilderTests.cs

Config builders are used for Request Builder unit tests to simplify the tests.

#76449 - use builders for Request Builder unit tests

---

src/Tests/CaptainHook.Tests/Web/FlowTests/E2EFlowTestsFixture.cs
src/Tests/CaptainHook.Tests/Web/FlowTests/FlowIntegrationTests.cs
src/Tests/CaptainHook.Tests/Web/FlowTests/FlowTestPredicateBuilder.cs

Refactored the integration tests to have a clearer flow.
Renamed test method names.

Task 78148 refactor integration tests flow

---

src/Tests/CaptainHook.Application.Tests/Handlers/UpsertWebhookRequestHandlerTests.cs

Simplify some tests after going through https://github.com/eShopWorld/captain-hook/pull/186

Simplify some unit tests for UpsertWebhookRequestHandlerTests

---

src/CaptainHook.Application/Handlers/Subscribers/DeleteWebhookRequestHandler.cs
src/CaptainHook.Application/Handlers/Subscribers/UpsertSubscriberRequestHandler.cs
src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs
src/CaptainHook.Application/Infrastructure/ContainerBuilderExtensions.cs
src/CaptainHook.Application/Infrastructure/ExceptionHandlingPipelineBehavior.cs
src/CaptainHook.Application/Infrastructure/ValidatorPipelineBehavior.cs
src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DeleteWebhookRequestHandlerTests.cs
src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/UpsertSubscriberRequestHandlerTests.cs
src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/UpsertWebhookRequestHandlerTests.cs
src/Tests/CaptainHook.Application.Tests/MediatorPipelineBehaviorsTests.cs

try-catch removed from Handlers
not longer relevant tests removed

ExceptionHandlingPipelineBehavior implemented

---

src/CaptainHook.Api/Controllers/EventsController.cs

Fix the Swagger UI issue by avoiding duplicate action names

Fix Swagger UI issue

---

src/CaptainHook.Api/CaptainHook.Api.csproj
src/CaptainHook.Application/CaptainHook.Application.csproj
src/CaptainHook.Cli/CaptainHook.Cli.csproj
src/CaptainHook.Common/CaptainHook.Common.csproj
src/CaptainHook.DirectorService/CaptainHook.DirectorService.csproj
src/CaptainHook.Domain/CaptainHook.Domain.csproj
src/CaptainHook.EventHandlerActor/CaptainHook.EventHandlerActor.csproj
src/CaptainHook.EventReaderService/CaptainHook.EventReaderService.csproj
src/CaptainHook.Telemetry/CaptainHook.Telemetry.csproj
src/Tests/CaptainHook.Api.Tests/CaptainHook.Api.Tests.csproj
src/Tests/CaptainHook.Application.Tests/CaptainHook.Application.Tests.csproj
src/Tests/CaptainHook.Cli.Tests/CaptainHook.Cli.Tests.csproj
src/Tests/CaptainHook.Domain.Tests/CaptainHook.Domain.Tests.csproj
src/Tests/CaptainHook.EventHandlerActor.Tests/CaptainHook.EventHandlerActor.Tests.csproj
src/Tests/CaptainHook.Storage.Cosmos.Tests/CaptainHook.Storage.Cosmos.Tests.csproj
src/Tests/CaptainHook.Telemetry.Tests/CaptainHook.Telemetry.Tests.csproj
src/Tests/CaptainHook.Tests/CaptainHook.Tests.csproj
src/Tests/CaptainHook.TestsInfrastructure/CaptainHook.TestsInfrastructure.csproj

This is a maintenance PR to update all non-SF related package dependencies for Captain Hook to the latest version.

Upgrade dependencies

---

src/CaptainHook.Api/Controllers/EventsController.cs
src/CaptainHook.Storage.Cosmos/Models/AuthenticationSubdocument.cs

- Cosmos serialization was failing due to missing attributes
- Added missing Swagger attribute

#82398 Fix Cosmos DB serialization

---

src/CaptainHook.Common/CaptainHook.Common.csproj
src/CaptainHook.EventHandlerActor/CaptainHook.EventHandlerActor.csproj

Downgrade Eshopworld.Devops package from v. 5.1.6 to v. 5.0.1 for common project which is failing to authenticate against KV.

Downgrade Eshopworld.Devops

---

src/Platform.Eda.Cli/Platform.Eda.Cli.csproj
src/Platform.Eda.Cli/appsettings.CI.json
src/Platform.Eda.Cli/appsettings.DEVELOPMENT.json
src/Platform.Eda.Cli/appsettings.PREP.json
src/Platform.Eda.Cli/appsettings.PROD.json
src/Platform.Eda.Cli/appsettings.SAND.json
src/Platform.Eda.Cli/appsettings.TEST.json
src/Platform.Eda.Cli/appsettings.json

The secrets are not in key-vaults yet. As soon as this is accepted I am going to prepare a PR in the other repo to push them.

#86704 - prepare configuration for environments

---

src/CaptainHook.Api.Client/ApiClient/Models/CaptainHookContractSubscriberDto.cs
src/CaptainHook.Api.Client/ApiClient/Models/CaptainHookContractWebhooksDto.cs
src/Tests/Platform.Eda.Cli.Tests/Commands/ConfigureEda/SubscribersDirectoryProcessorTests.cs

Regenrated API client and Added test to cover the Json parsing bug.

Fixed - EDA CLI - subscriber data not fully passed

---

src/Platform.Eda.Cli/appsettings.PROD.json
src/Platform.Eda.Cli/appsettings.SAND.json

Nobody has noticed that, not the author not the reviewers. I guess we will never learn the location of those services by heart :)

#87853 - reconfigure cli for sand and prod

---

src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/SubscribersDirectoryProcessor.cs

Fixes the error in CLI pipeline. The complete code is a WIP on task 88419.

Temporarily removed empty directory error.

---

src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/PutSubscriberProcessChain.cs
src/Tests/Platform.Eda.Cli.Tests/Commands/ConfigureEda/Processor/PutSubscriberProcessChainTests.cs

Return 1 if any file processing fails.

---

src/Platform.Eda.Cli/Extensions/ExceptionExtensions.cs
src/Platform.Eda.Cli/Program.cs

Let's print the message of inner exceptions (if present) to improve the debugging

#89940 Improve CLI error logging

---

src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/PutSubscriberProcessChain.cs

Prints the File Validation success message when NoDryRun is false.

Removed File OK validation output when running against environment

---

src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
src/Tests/CaptainHook.Application.Tests/Infrastructure/SubscriberEntityToConfigurationMapperTests/WebhookAndCallbacksMapSubscriberAsyncTests.cs

See the bug description for more details

#92052 - map timeouts and other for single webhooks

---

src/CaptainHook.EventHandlerActor/Handlers/Requests/BuildUriContext.cs
src/CaptainHook.EventHandlerActor/Handlers/Requests/DefaultRequestBuilder.cs
src/Tests/CaptainHook.EventHandlerActor.Tests/Handlers/Requests/BuildUriContextTests.cs

Since I wasn't able to find the root cause for the errors in AI. I am logging more information around the creation of Uris. This should help us understand the problem getter.

#92380 - extend logging for invalid uris

---

src/CaptainHook.EventHandlerActor/Handlers/Requests/RouteAndReplaceRequestBuilder.cs
src/Tests/CaptainHook.EventHandlerActor.Tests/Handlers/Requests/RouteAndReplaceRequestBuilderTests.cs

Ignore missing properties as we used to so far

#92569 - replace values which are provided (regardless of the value)

---

src/CaptainHook.Benchmark/Program.cs
src/CaptainHook.DirectorService/DirectorService.cs
src/CaptainHook.EventReaderService/EventReaderService.cs

Bugs - https://sonarcloud.io/project/issues?id=esw.captain-hook&open=AXLsA35OHE1eOavyJyNB&resolved=false&types=BUG

Fixed sonar cloud bugs

---

src/CaptainHook.Api/Startup.cs
src/CaptainHook.Common/Configuration/ConfigurationSettings.cs
src/CaptainHook.Common/Configuration/TempConfigLoader.cs
src/CaptainHook.Common/Telemetry/TelemetryExtensions.cs
src/CaptainHook.DirectorService/Program.cs
src/CaptainHook.EventHandlerActor/Program.cs
src/CaptainHook.EventReaderService/Program.cs
src/CaptainHook.Fabric/ApplicationParameters/CI.xml

Added support for separate Instrumentation (Platform AI) and Internal (Tooling AI) keys.
Won't be merged until both keys are properly set on all environments.

101924 telemetry keys improvements

---

src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
src/CaptainHook.EventHandlerActor/Utils/DictionaryExtensions.cs

Fixed logging of RequestHeaders and Authorization token.

107415 RequestLogger fixes

---

src/Tests/CaptainHook.Api.Tests/Integration/EventsControllerTests.cs
src/Tests/CaptainHook.Api.Tests/TestOutputHelperExtensions.cs

Release with this code has succeeded: Release-674-1.1.0+1788

Additional logging for integration tests
