src/CaptainHook.EventHandlerActor/EventHandlerActor.cs, src/CaptainHook.EventHandlerActor/Handlers/GenericWebhookHandler.cs, src/CaptainHook.EventHandlerActor/Handlers/HttpClientExtensions.cs, src/CaptainHook.EventHandlerActor/Handlers/HttpResponseMessageExtensions.cs, src/CaptainHook.EventHandlerActor/Handlers/IHandler.cs, src/CaptainHook.EventHandlerActor/Handlers/WebhookResponseHandler.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/GenericWebhookHandlerTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/HttpResponseMessageTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/WebhookResponseHandlerTests.cs, src/nuget.config
This changes the flow for new definition of codes that are considered "failed delivery"  - 5XX and 429
also repointed packages folder to structure to match what is in the sfproj file
=> Fix hook and callback delivery failure handling

src/CaptainHook.Database/Setup/CosmosDbConfigurationExtensions.cs, src/CaptainHook.Database/Setup/DbSettingsParser.cs, src/CaptainHook.DirectorService/CaptainHook.DirectorService.csproj, src/CaptainHook.DirectorService/PackageRoot/ServiceManifest.xml, src/CaptainHook.DirectorService/Program.cs, src/CaptainHook.Fabric/ApplicationPackageRoot/ApplicationManifest.xml, src/CaptainHook.Fabric/ApplicationParameters/Local.1Node.xml
Configure CosmosDB via Environment variables.
Temporarily we want to use Env variables to configure connection string to CosmosDB since the local emulator will be used. Long term, an Azure instance will be used and configured through KeyVaults. The run of the code is disabled until a feature flag is introduced.
=> #57444 - configure connection with CosmosDB

src/CaptainHook.Common/CaptainHook.Common.csproj, src/CaptainHook.Common/Configuration/FeatureFlags/CosmosDbFeatureFlag.cs, src/CaptainHook.Common/Configuration/FeatureFlags/FeatureFlagBase.cs, src/CaptainHook.Common/Configuration/FeatureFlagsConfiguration.cs, src/CaptainHook.DirectorService/Program.cs, src/Tests/CaptainHook.Tests/Configuration/FeatureFlags/CosmosDbFeatureFlagTests.cs, src/Tests/CaptainHook.Tests/Configuration/FeatureFlagsConfigurationTests.cs
Simple Feature Flag functionality to enable/disable features by provided configuration.
CosmosDb configuration is going to live for now in the designated environments. We want to keep merging to master though and for that reason, we need to isolate the functionality with the use of feature flags.
=> Story 57196 feature flags

src/Tests/CaptainHook.Tests/CaptainHook.Tests.csproj
Reference EShopworld.Messaging package directly as it should have been from the beginning. Right now the old version of 1.1.1 is referenced causing issues in runtime for L1 tests.
=> #62771 - fix failing integration tests due to invalid Messaging reference

src/codecoverage.runsettings, src/global.json
Test fix for captain-hook after core 3.1 migration.
The second part of fix was to enable build cleanup in pipeline configuration on ADO.
=> 62726 unit tests discrepancies fix

src/CaptainHook.Common/Telemetry/Service/EventReader/ServiceBusReconnectionAttemptEvent.cs, src/CaptainHook.EventReaderService/CaptainHook.EventReaderService.csproj, src/CaptainHook.EventReaderService/EventReaderService.cs
On EventReaderService.cs the catch block for the ServiceBusCommunicationException has been augmented with a retry policy on the Service Bus setup method to allow for a recovery when the connection drop lasts longer. The strategy is an exponential backoff.
A custom AI event is logged (ServiceBusReconnectionAttemptEvent) carrying the retry count so that appropriate alerting can be later set up.
=> #65429 - retry service bus setup when connection is dropped

src/CaptainHook.Api/CaptainHook.Api.cs, src/CaptainHook.Api/CaptainHook.Api.csproj, src/CaptainHook.Api/PackageRoot/Config/Settings.xml, src/CaptainHook.Api/PackageRoot/ServiceManifest.xml, src/CaptainHook.Api/Program.cs, src/CaptainHook.Api/ServiceConfigurationOptions.cs, src/CaptainHook.Api/ServiceEventSource.cs, src/CaptainHook.Api/Startup.cs, src/CaptainHook.Api/appsettings.CI.json, src/CaptainHook.Api/appsettings.Development.json, src/CaptainHook.Api/appsettings.PREP.json, src/CaptainHook.Api/appsettings.PROD.json, src/CaptainHook.Api/appsettings.SAND.json, src/CaptainHook.Api/appsettings.TEST.json, src/CaptainHook.Api/appsettings.json, src/CaptainHook.Common/ServiceNaming.cs, src/CaptainHook.DirectorService/DirectorService.cs, src/CaptainHook.Fabric/ApplicationPackageRoot/ApplicationManifest.xml, src/CaptainHook.Fabric/ApplicationParameters/Local.1Node.xml, src/CaptainHook.Fabric/CaptainHook.Fabric.sfproj, src/CaptainHook.sln
Changes which add Web Api to Captain Hook and host it within Service Fabric. The Api supports /probe endpoint only at this stage.
The Web API is going to be used to control Captain Hook configuration in the long term.
=> #67466 - add web api to Captain Hook

src/CaptainHook.Api/Controllers/RefreshConfigController.cs, src/CaptainHook.Api/Models/RefreshConfigRequest.cs, src/CaptainHook.Common/Remoting/IDirectorServiceRemoting.cs, src/CaptainHook.Common/ServiceNaming.cs, src/CaptainHook.DirectorService/DirectorService.cs
A simple controller along with the remoting service client are set up to demonstrate the communication between two components.
The current implementation takes the event name and as an example returns the counter of configurations of valid subscribers to that event that are found in Director Service. This logic can be extended now that the base is ready.
=> #67475 - establish remoting betwen API and Director Service

src/CaptainHook.Cli.Tests/GenerateJson/EventTests.cs, src/CaptainHook.Cli.Tests/GeneratePowerShell/ConfigDirectoryProcessorTests.cs, src/CaptainHook.Cli.Tests/SampleFile.ps1, src/CaptainHook.Common/Configuration/EventHandlerConfig.cs, src/CaptainHook.Common/ServiceModels/EventReaderInitData.cs, src/CaptainHook.EventReaderService/EventReaderService.cs, src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderInitDataTests.cs
Introduce a toggle which allows us to enable/disable the heart beat per subscriber. By default it is going to be disabled.
`setConfig 'event--1--heartbeatinterval' '00:00:05' $KeyVault`
Use TimeSpan values to provide the wait interval. Remove the entry to disable heart beat.
Reload fully supported.
=> #72613 - introduce heart beat toggle on the subscriber level

src/CaptainHook.Cli.Tests/GenerateJson/EventTests.cs, src/CaptainHook.Cli.Tests/GeneratePowerShell/ConfigDirectoryProcessorTests.cs, src/CaptainHook.Cli.Tests/SampleFile.ps1, src/CaptainHook.Common/Configuration/EventHandlerConfig.cs, src/CaptainHook.Common/ServiceModels/EventReaderInitData.cs, src/CaptainHook.EventReaderService/EventReaderService.cs, src/CaptainHook.EventReaderService/HeartBeat/HeartBeatStats.cs, src/CaptainHook.EventReaderService/HeartBeat/ReaderHeartBeatEvent.cs, src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderInitDataTests.cs, src/Tests/CaptainHook.Tests/Services/Reliable/HeartBeat/HeartBeatStatsTests.cs
Heart Beat telemetry event for Event Reader is sent on a regular interval
We want to learn certain properties of Event Reader operations which we can then put on a graph to understand the change in behaviour over time. Especially we are going to be able to monitor communication with Service Bus and potential issues there.
Things to be added (separate PR):
- conditional logic to control whether heartbeat is enabled or disabled and control the publish period (will be done on the subscriber level)
- counter for delivered/undelivered messages to be added
=> #72356 - add reader heart beat

src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderTests.cs
Required to handle heart beat initialisation
=> #72356 - fix failing tests by explicitly calling OnOpenAsync

src/CaptainHook.DirectorService/DirectorService.cs, src/CaptainHook.DirectorService/Infrastructure/ConfigurationMerger.cs, src/CaptainHook.DirectorService/Infrastructure/ReaderServicesManager.cs, src/CaptainHook.Domain/Entities/SubscriberEntity.cs, src/CaptainHook.Storage.Cosmos/Models/EndpointDocument.cs, src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs, src/Tests/CaptainHook.Storage.Cosmos.Tests/SubscriberRepositoryTests.cs, src/Tests/CaptainHook.Tests/Builders/SubscriberBuilder.cs, src/Tests/CaptainHook.Tests/Director/ConfigurationMergerTests.cs
This PR enables MERGE and RELOAD which were both broken for config changes. *Please ensure to question every line, this PR is ⚠️ crucial*
Locally, the following has been tested:
- config in KV
- config in KV and Cosmos independent
- config in KV and Cosmos and KV changed and reloaded
- config in KV and Cosmos and Cosmos changed and reloaded
- config in KV and Cosmos override
- config in KV and Cosmos override changed and reloaded
I am going to perform more tests while this PR is being reviewed.
=> #73562 - ensure Merge uses EventType and SubscriberName for matching

src/CaptainHook.Api/CaptainHook.Api.csproj, src/CaptainHook.Cli/CaptainHook.Cli.csproj, src/CaptainHook.Common/CaptainHook.Common.csproj, src/CaptainHook.DirectorService/CaptainHook.DirectorService.csproj, src/CaptainHook.EventHandlerActor/CaptainHook.EventHandlerActor.csproj, src/CaptainHook.EventReaderService/CaptainHook.EventReaderService.csproj, src/CaptainHook.Fabric/CaptainHook.Fabric.sfproj, src/CaptainHook.Fabric/packages.config, src/CaptainHook.Interfaces/CaptainHook.Interfaces.csproj, src/CaptainHook.Telemetry/CaptainHook.Telemetry.csproj, src/Tests/CaptainHook.Api.Tests/CaptainHook.Api.Tests.csproj, src/Tests/CaptainHook.Api.Tests/config/ApiClientFixture.cs, src/Tests/CaptainHook.Cli.Tests/CaptainHook.Cli.Tests.csproj, src/Tests/CaptainHook.Telemetry.Tests/CaptainHook.Telemetry.Tests.csproj, src/Tests/CaptainHook.Tests/CaptainHook.Tests.csproj
All packages have been upgraded to the latest stable version except for Microsoft.Extensions.Configuration.AzureKeyVault which is known in ESW to cause a timeout on any version higher than v. 2.2.0 when concurrently loading a large amount of secrets from a single keyvault.
=> #72765 Upgrade all packages to the latest stable version

src/CaptainHook.Api/CaptainHook.Api.csproj, src/CaptainHook.DirectorService/CaptainHook.DirectorService.csproj, src/CaptainHook.EventHandlerActor/CaptainHook.EventHandlerActor.csproj, src/CaptainHook.EventReaderService/CaptainHook.EventReaderService.csproj, src/CaptainHook.Interfaces/CaptainHook.Interfaces.csproj, src/CaptainHook.Telemetry/CaptainHook.Telemetry.csproj, src/Tests/CaptainHook.Tests/CaptainHook.Tests.csproj
We are downgrading SF libraries to v. 4.0.470 until the cluster are upgraded to v.7.1.x due to incompatibility.
=> Downgrade of SF libraries to v. 4.0.470

src/Tests/CaptainHook.Tests/Director/SubscriberConfigurationLoaderTests.cs
This test needs a env variable configured with the KV to run. So excluding for now so we can satisfactorily run after CI deploy.
=> Temporarily move KV test out of unit testing

src/CaptainHook.EventReaderService/EventReaderService.cs
Close reader explicitly
High number of `QuotaExceededException`s are thrown. The reader is now closed explicitly in the hope this is going to address the problem. Initial tests are positive. After having deployed to CI and TEST the exceptions have not appeared within 1h after the deploy.
=> #75736 - explicitly close reader

src/CaptainHook.Api/CaptainHook.Api.csproj, src/CaptainHook.Api/PackageRoot/ServiceManifest.xml, src/CaptainHook.Api/Startup.cs, src/CaptainHook.Common/CaptainHook.Common.csproj, src/CaptainHook.Common/Configuration/TempConfigLoader.cs, src/CaptainHook.Fabric/ApplicationPackageRoot/ApplicationManifest.xml
Use the TempConfigLoader in the API project to avoid loading the entire KV, in order to improve the API bootstrap time.
Also cleaned up some unused packages.
=> Use temp config loader for API project

src/CaptainHook.EventHandlerActor/Handlers/RequestBuilder.cs, src/Tests/CaptainHook.Tests/Configuration/RequestBuilderTests.cs
The URI builder will produce an invalid URI if the payload parameter is not URI safe. Therefore the HTTP call will most likely fail at the other end.
This PR addresses the issue by encoding any parameter appended at the end of the URI.
=> Escape URI parameter from payload

src/CaptainHook.Benchmark/Program.cs, src/CaptainHook.Cli/Commands/GenerateJson/GenerateJsonCommand.cs, src/CaptainHook.Cli/Common/ShouldSerializeContractResolver.cs, src/CaptainHook.Common/Configuration/EventHandlerConfig.cs, src/CaptainHook.Common/Configuration/SourceParserLocation.cs, src/Tests/CaptainHook.Tests/Builders/WebhookRequestRuleBuilder.cs, src/Tests/CaptainHook.Tests/Configuration/RequestBuilderTests.cs, src/Tests/CaptainHook.Tests/Services/MessageDataSerializationTests.cs, src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderInitDataTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/GenericWebhookHandlerTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/WebhookResponseHandlerTests.cs
Parser Location is extended to facilitate a collection of Replace entries
We want to be able to extend CH with Replace transformation without affecting the existing code. New class to handle Source is created.
Json entry:
```json
{
"Source": {
"Replace": {
"ordercode": "$.OrderCode",
"selector": "$.TenantCode"
}
},
"Destination": {
"RuleAction": "Route"
},
"Routes": [
{...
```
Powershell
```ps1
setConfig 'event--26--webhookconfig--webhookrequestrules--2--source--replace--selector' '$.TenantCode' $KeyVault
setConfig 'event--26--webhookconfig--webhookrequestrules--2--source--replace--ordercode' '$.OrderCode' $KeyVault
```
=> Task 75634 extend source config with replace option

src/CaptainHook.Common/Configuration/EventHandlerConfig.cs, src/CaptainHook.EventHandlerActor/HandlerModule.cs, src/CaptainHook.EventHandlerActor/Handlers/Requests/DefaultRequestBuilder.cs, src/CaptainHook.EventHandlerActor/Handlers/Requests/RequestBuilderDispatcher.cs, src/CaptainHook.EventHandlerActor/Handlers/Requests/RouteAndReplaceRequestBuilder.cs, src/CaptainHook.EventHandlerActor/Program.cs, src/Tests/CaptainHook.Tests/Configuration/RequestBuilderTests.cs, src/Tests/CaptainHook.Tests/Services/Actors/Requests/RequestBuilderDispatcherTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/GenericWebHookHandlerVerbTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/GenericWebhookHandlerTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/WebhookResponseHandlerTests.cs
Introduces a backbone to implement the logic for request builder where RouteAndReplace mechanism is going to be used. Logic itself is yet to be implemented.
1. DefaultRequestBuilder (renamed from RequestBuilder) is the previous implementation of the builder
2. RequestBuilderDispatcher decides which builder to use
3. RouteAndReplaceRequestBuilder is the backbone for the new request builder for Route and Replace. Yet to be implemented fully.
=> #75635 - add request builder for Route and Replace

src/CaptainHook.EventHandlerActor/Handlers/Requests/DefaultRequestBuilder.cs, src/CaptainHook.EventHandlerActor/Handlers/Requests/RouteAndReplaceRequestBuilder.cs, src/Tests/CaptainHook.Tests/Configuration/RequestBuilderTests.cs, src/Tests/CaptainHook.Tests/Services/Actors/Requests/RouteAndReplaceRequestBuilderTests.cs
During event migration and testing I have realised that the config selection takes place later in the algorithm to create httpclient and to cache it. The code has been refactored to address this.
At the same time I have realised that public method is not tested by unit tests. Those have now been added for Default and New Request Builder.
=> #76336 - implement webhook selection for RouteAndReplace

src/CaptainHook.Cli/Commands/GenerateJson/GenerateJsonCommand.cs, src/CaptainHook.Common/Configuration/ConfigParser.cs, src/CaptainHook.Common/Configuration/Configuration.cs, src/Tests/CaptainHook.Tests/Configuration/KeyVaultProviderTests.cs
Removal of URI validation which was intended to reuse hosts, but actually was never used. Through that mechanism, a placeholder in the host was unaccepted causing an exception. This is not something that config loader should occupy itself with. The endpointlist collection was not used anyway so I have decided to remove it.
=> #76794 - remove unused url validation preventing uri replacement

src/CaptainHook.EventHandlerActor/Handlers/HttpClientFactory.cs, src/CaptainHook.EventHandlerActor/Handlers/Requests/BuildUriContext.cs
Placeholder in the host broke the algorithm. Its presence in other parts is accepted, however. This is a blunt fix as I wasn't able to achieve a design I originally wanted without changing the implementation extensively.
=> #76794 - remove placeholders for http client caching

src/CaptainHook.EventHandlerActor/Handlers/Requests/DefaultRequestBuilder.cs, src/CaptainHook.EventHandlerActor/Handlers/Requests/RouteAndReplaceRequestBuilder.cs, src/Tests/CaptainHook.Tests/Services/Actors/Requests/RouteAndReplaceRequestBuilderTests.cs
Route and Replace incorrectly used HTTP verb for its requests. The current PR changes that by using the HTTP verb defined for the particular endpoint.
=> #77383 - include http verb for route and replace

src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs, src/CaptainHook.Domain/Entities/EndpointEntity.cs, src/CaptainHook.Storage.Cosmos/Models/EndpointSubdocument.cs, src/CaptainHook.Storage.Cosmos/Models/EndpointType.cs, src/CaptainHook.Storage.Cosmos/Models/SubscriberDocument.cs, src/CaptainHook.Storage.Cosmos/Models/UriTransformDocument.cs, src/CaptainHook.Storage.Cosmos/Models/WebhookType.cs, src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs, src/Tests/CaptainHook.Application.Tests/Handlers/UpsertWebhookRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/SubscriberEntityToConfigurationMapperTests.cs, src/Tests/CaptainHook.Storage.Cosmos.Tests/SubscriberRepositoryTests.cs, src/Tests/CaptainHook.Tests/Director/ConfigurationMergerTests.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/SubscriberBuilder.cs
This is a quick PR to address the cosmos side of things. With these changes API put endpoint request is going to be stored to cosmos. The mapping however need to be worked out.
=> Task 77087 persist scope uri transform in cosmos

src/CaptainHook.EventHandlerActor/Handlers/EventHandlerFactory.cs, src/CaptainHook.EventHandlerActor/Handlers/GenericWebhookHandler.cs, src/CaptainHook.EventHandlerActor/Handlers/IEventHandlerFactory.cs
This change must be deployed first to support backward compatibility.
=> Usages of MessageData.WebhookConfig removed from Actor

src/CaptainHook.Application/Handlers/Subscribers/UpsertSubscriberRequestHandler.cs, src/CaptainHook.Application/Requests/Subscribers/UpsertSubscriberRequest.cs, src/CaptainHook.Contract/EndpointDto.cs, src/CaptainHook.Domain/Entities/SubscriberEntity.cs, src/CaptainHook.Domain/Entities/WebhooksEntity.cs, src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/UpsertSubscriberRequestHandlerTests.cs, src/Tests/CaptainHook.Storage.Cosmos.Tests/SubscriberRepositoryTests.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/SubscriberDtoBuilder.cs
The new handler is added. We have noticed that it is very similar to the Webhook Handler and it is likely that we are going to unify them at the next stage.
Code works and stores to Cosmos however not all mapping might be valid at this stage. JSON to test with (example):
```json
{
"webhooks": {
"selectionRule": "$.TestSelector",
"endpoints": [
{
"uri": "https://webhook.site/a86944ce-b402-493b-ae57-1d679da8d82b",
"httpVerb": "POST",
"authentication": {
"type": "OIDC",
"clientId": "abc",
"uri": "https://webhook.site/a86944ce-b402-493b-ae57-1d679da8d82b",
"clientSecret": {
"vault": "abc-keyvault",
"name": "event--1--webhookconfig--authenticationconfig--clientsecret"
},
"scopes": [
"scope1"
]
}
}
]
}
}
```
=> #78982 - add handler for subscriber request

src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs, src/CaptainHook.Application.Infrastructure/DirectorService/IDirectorServiceProxy.cs, src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs, src/CaptainHook.Domain/Repositories/ISubscriberRepository.cs, src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs, src/Tests/CaptainHook.Application.Tests/Handlers/UpsertWebhookRequestHandlerTests.cs
Handler gets extended so that it can handle both Additions and Updates. Updates always go through but do not have any effect in Director Service or Cosmos just yet.
=> #78987 - handler to accept additional endpoints for subscriber

src/CaptainHook.Api/Controllers/SubscribersController.cs
Quick PR to address stuff I stumbled upon while working on something else:
- Return 500 when there's an exception (400 bad request has a different meaning)
- Correctly use ToExceptionEvent to log BB exception
- Return 503 when director has not completed loading of config (config is unavailable, subscribers is null, then we would be getting a 400)
- Set Swagger response descriptions
=> Return appropriate error when config has not been fully loaded yet

src/CaptainHook.Domain/Entities/SubscriberEntity.cs, src/CaptainHook.Storage.Cosmos/Models/SubscriberDocument.cs, src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs, src/Tests/CaptainHook.Storage.Cosmos.Tests/SubscriberRepositoryTests.cs
Start using eTags for document updates/replacements. Further logic to address failures for updates is going to be addressed in a separate PR.
=> #78991 - start using eTags for updates in Cosmos DB

src/CaptainHook.Application/CaptainHook.Application.csproj, src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs, src/Tests/CaptainHook.Application.Tests/Handlers/UpsertWebhookRequestHandlerTests.cs
Operations are retried if there is a problem when updating the document in Cosmos (changes in between and eTag check fails). Please note this also applies to the subscriber being removed entirely, in that case, we will re-add it with a single endpoint.
=> #78993 - support retries for Upsert Webhook Request

src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/SubscriberEntityToConfigurationMapperTests.cs
- Use a case insensitive comparison when finding duplicates in the URI transform replacement dictionary
- Use a case insensitive comparer when building the aggregate dictionary so the subsequent override of the selector key will work as expected in any case
- Override the selector replacement in the URI transform with the selectionRule
=> Override selector replace transform with selection rule and unit test

src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/SubscriberEntityToConfigurationMapperTests.cs
The lack of this broke insert of a webhook for a new subscriber (when a new subscriber is created from webhook PUT endpoint).
=> #80130 - use endpoint selector if no selection rule provided

src/CaptainHook.Api.Client/ApiClient/CaptainHookClient.cs, src/CaptainHook.Api/Controllers/RefreshConfigController.cs, src/CaptainHook.Api/Controllers/SubscribersController.cs
Background - The 401 is part of the GetAll API behavior but not the documentation (swagger.json) due to the missing annotation. This makes the CaptainHook.Api.Client throw an exception when 401 is returned and the tests fail.
=> Added 401 response type annotation. Regenerated client.

src/CaptainHook.Api/Controllers/EventsController.cs, src/CaptainHook.Api/Controllers/SubscribersController.cs
The GetAll Subscribers API had a check in place to ensure the Director service completed the loading of subscribers before returning a result. This check was relying on the subscribers dictionary being null while the loading is still in progress. Then the API could reply with a 503 informing the user the load had not been completed yet. This scenario applies when starting the application.
This check was broken by a subsequent commit which initialized the subscriber with an empty Dictionary.
This PR address this issue by checking for an empty dictionary instead of null.
This is not an ideal situation as an empty Dictionary could still be a valid dictionary.
=> Fix Subscribers loading issue

src/Tests/CaptainHook.Api.Tests/Api/RefreshConfigControllerTests.cs
The CI deployment fails due to failed integration tests.
=> Skip refresh config on builds

src/CaptainHook.Api.Client/ApiClient/CaptainHookClient.cs, src/CaptainHook.Api.Client/ApiClient/CaptainHookClientExtensions.cs, src/CaptainHook.Api.Client/ApiClient/ICaptainHookClient.cs, src/CaptainHook.Api/Controllers/ConfigurationController.cs, src/CaptainHook.Api/Controllers/SubscribersController.cs, src/CaptainHook.Api/Startup.cs, src/CaptainHook.Application.Infrastructure/DirectorService/Remoting/IDirectorServiceRemoting.cs, src/CaptainHook.Application.Infrastructure/DirectorService/Remoting/ReloadConfigurationStatus.cs, src/CaptainHook.DirectorService/DirectorService.cs, src/Tests/CaptainHook.Api.Tests/Api/RefreshConfigControllerTests.cs
We have extended the APi with api/config/status endpoint which returns 200 if config has been loaded and 202 if the load is in progress. The choice of status codes was arbitrary and discussed within the team (also documented in UI).
The status code is going to be used in integration tests to wait for the reload to finish. It has been decided by the team that it is a better decision to extend the API than address the problem in another way.
=> Task 80579 extend ch api with reload status

src/CaptainHook.Api/Controllers/EventsController.cs
The Swagger attribute looks incorrect on the DeleteWebhook API endpoint.
=> Use correct Swagger attribute for DeleteWebhook endpoint

src/Tests/CaptainHook.Api.Tests/CaptainHook.Api.Tests.csproj
The `CaptainHook.Api.Tests` project fails to load due to a "File cannot depend on itself" error. Didn't get this error until I restarted VS yesterday.
=> Fix ch api test project load error

src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderTests.cs
EventReaderServiceTests contains a lot of code duplicated in every method.
Also one of the tests (`InitSubscriberDataIsPassedToHandlers`) was false positive because of invalid assertion logic.
Such assertion: 
```
collection.Should().AllBeEquivalentTo(new SubscriberConfiguration { EventType = eventName, SubscriberName = "subA" });
```
won't fail if `collection` is empty. It might seem counter-intuitive at the first glance but it's logical. 
So if we'd like to perform `AllBeEquivalentTo` assertion we should first check if collection is not empty.
=> Event reader service tests fix

src/CaptainHook.Api/Controllers/EventsController.cs, src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs, src/CaptainHook.Application/Requests/Subscribers/UpsertWebhookRequest.cs, src/CaptainHook.Application/Validators/DeleteWebhookRequestValidator.cs, src/CaptainHook.Application/Validators/Dtos/UpsertEndpointDtoValidator.cs, src/CaptainHook.Application/Validators/Dtos/UpsertSubscriberEndpointDtoValidator.cs, src/CaptainHook.Application/Validators/Dtos/WebhooksDtoValidator.cs, src/CaptainHook.Application/Validators/UpsertWebhookRequestValidator.cs, src/CaptainHook.Domain/Entities/EndpointEntity.cs, src/CaptainHook.Domain/Entities/WebhooksEntityValidator.cs, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/UpsertWebhookRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/RequestValidators/DeleteWebhookRequestValidatorTests.cs, src/Tests/CaptainHook.Application.Tests/RequestValidators/UpsertSubscriberRequestValidatorTests.cs, src/Tests/CaptainHook.Application.Tests/RequestValidators/UpsertWebhookRequestValidatorTests.cs, src/Tests/CaptainHook.Application.Tests/Validators/Dtos/UpsertEndpointDtoValidatorTests.cs, src/Tests/CaptainHook.Application.Tests/Validators/Dtos/UpsertSubscriberEndpointDtoValidatorTests.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/EndpointDtoBuilder.cs
This PR focuses on two main aspects:
1. Specify endpoint selector in the uri
2. Use * as the default selector (instead of null previously)
The API endpoints are not duplicated now as both PUT and DELETE can handle selectors:
The information on * is also provided is Swagger UI for visual support:
=> #80115 - provide endpoint selector identifier in the uri, use * as default

src/CaptainHook.Application.Infrastructure/CaptainHook.Application.Infrastructure.csproj, src/CaptainHook.Application.Infrastructure/Mappers/DtoToEntityMapper.cs, src/CaptainHook.Application.Infrastructure/Mappers/IDtoToEntityMapper.cs, src/CaptainHook.Application/ApplicationModule.cs, src/CaptainHook.Application/Handlers/Subscribers/DeleteWebhookRequestHandler.cs, src/CaptainHook.Application/Handlers/Subscribers/UpsertSubscriberRequestHandler.cs, src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs, src/CaptainHook.Fabric/ApplicationParameters/Local.1Node.xml, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DeleteWebhookRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/UpsertSubscriberRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/UpsertWebhookRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/DtoToEntityMapperTests.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/BasicAuthenticationDtoBuilder.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/OidcAuthenticationDtoBuilder.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/UriTransformDtoBuilder.cs
The mapping code from DTOs to Entities has been extracted from handlers and moved to a separate service so all handlers can share the same piece of code.
=> #82366 DTO to Entity mapper service & tests

src/CaptainHook.Application.Infrastructure/Mappers/DtoToEntityMapper.cs, src/CaptainHook.Application.Infrastructure/Mappers/IDtoToEntityMapper.cs, src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/UpsertWebhookRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/DtoToEntityMapperTests.cs
For Webhook/Endpoint PUT requests, the selector has to be taken from the request itself. For Subscriber PUT requests it is taken from the payload. That small difference was lost during mapping creations.
=> Task 82576 enable selector mapping for requests

src/CaptainHook.Api.Client/ApiClient/CaptainHookClient.cs, src/CaptainHook.Api.Client/ApiClient/CaptainHookClientExtensions.cs, src/CaptainHook.Api.Client/ApiClient/ICaptainHookClient.cs, src/CaptainHook.Api/Controllers/EventsController.cs, src/CaptainHook.Api/Controllers/SubscribersController.cs, src/Tests/CaptainHook.Api.Tests/Integration/EventsControllerTests.cs, src/Tests/CaptainHook.Api.Tests/Integration/SubscribersControllerTests.cs
This is a different implementation of the Get Subscriber API which comes after a conversation with @chomick .
The endpoint has been moved to the Subscriber controller to leave the Event one clean and consistent with the rest of the architecture. The new Get operation resides in the temporary Subscriber controller along with the GetAll where does not utilizes a well-defined contract until the whole API is complete.
=> #82787 Get subscriber details via API

src/CaptainHook.Cli/Commands/ConfigureEda/ApiClientFixture.cs, src/CaptainHook.Cli/Commands/ConfigureEda/ApiConsumer.cs, src/CaptainHook.Cli/Commands/ConfigureEda/ConfigureEdaCommand.cs, src/CaptainHook.Cli/Commands/ConfigureEda/ConsoleSubscriberWriter.cs, src/CaptainHook.Cli/Commands/ConfigureEda/Models/PutSubscriberFile.cs, src/CaptainHook.Cli/Commands/ConfigureEda/Models/PutSubscriberRequest.cs, src/CaptainHook.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs, src/CaptainHook.Cli/Program.cs
Since the command has changed, its namespaces should too.
=> #85983 - move configure eda command to a new namespace

src/CaptainHook.Cli/Commands/ConfigureEda/ApiConsumer.cs, src/CaptainHook.Cli/Commands/ConfigureEda/ConfigureEdaCommand.cs, src/CaptainHook.Cli/Commands/ConfigureEda/ConsoleSubscriberWriter.cs, src/CaptainHook.Cli/Commands/ConfigureEda/Models/ApiOperationResult.cs, src/CaptainHook.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
The goal is to be able for the CLI to process files/subscribers individually where error in one does not affect processing of the other. The output is also improved to reflect the fact that we now look into all the children folders and its files as well:
Remark:
No proper error handling is included at the moment, I will try to circle back here.
=> #86026 - process subscribers independently

src/CaptainHook.Application/Validators/Dtos/SubscriberDtoValidator.cs, src/CaptainHook.Cli/CaptainHook.Cli.csproj, src/CaptainHook.Contract/SubscriberDto.cs, src/Tests/CaptainHook.Application.Tests/RequestValidators/UpsertSubscriberRequestValidatorTests.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/SubscriberDtoBuilder.cs
With this change, I would like to suggest that:
1. The generated CLI will be `Platform.Eda.Cli.exe`
1. The project name remains `CaptainHook.Cli` in VS
1. The default namespace remains `CaptainHook.Cli`
Points 2 and 3 are mainly there to limit the changes, as by aligning everything we really don't benefit in anything.
Let me know what you think!
=> #86177 - rename the output cli to platform.eda.cli.exe

src/CaptainHook.Cli/CaptainHook.Cli.csproj, src/CaptainHook.Cli/Commands/ConfigureEda/ApiConsumer.cs, src/CaptainHook.Cli/Commands/ConfigureEda/ConfigureEdaCommand.cs, src/CaptainHook.Cli/Commands/ConfigureEda/ConsoleSubscriberWriter.cs
With this PR I am focusing on:
- handling errors with API communication and retrying 3 times total
- 201 and 202 are the only accepted answers
- success/failure status is output to the console using color
- some arguments are optimised
The result of the operation of the CLI:
=> Task 86026 process subscribers independently

src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs, src/CaptainHook.Domain/Entities/UriTransformEntity.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/SubscriberEntityToConfigurationMapperTests.cs
The issue originally comes from the Domain layer that is directly taking the cosmos replace dictionary to instantiate a new UriTransform entity. This entity will then carry over an instance of ReadOnlyDictionary which will fail when the EntityToSubscriberConfiguration mapper tries to add the selector to the replacements dictionary.
With this PR I have enforced the concept of having a ReadOnlyDictionary even at the domain layer level (so the tests that we're not failing before because of improper mapping, will fail then)
Then I have delegated the EntityToSubscriberConfiguration mapper to make a copy of the replacements dictionary before the manipulation. This brought the tests back to passing.
=> #86475 Deal with readonly dictionary in domain entity

src/Platform.Eda.Cli/Commands/ConfigureEda/ApiConsumer.cs, src/Platform.Eda.Cli/Commands/ConfigureEda/ConfigureEdaCommand.cs, src/Platform.Eda.Cli/Commands/ConfigureEda/Models/ApiOperationResult.cs, src/Platform.Eda.Cli/Commands/ConfigureEda/Models/PutSubscriberFile.cs, src/Tests/Platform.Eda.Cli.Tests/ConfigureEda/ApiConsumerTests.cs
With this PR I am covering ApiConsumer with unit tests. The reported coverage is 100% for dotCover.
1. SleepTimes are configurable to so that unit tests do not need to wait too long
2. App has been run locally to verify that it's working due to some refactorings made.
=> #86028 - cover ApiConsumer with unit tests

src/Platform.Eda.Cli/Commands/ConfigureEda/ApiConsumer.cs, src/Platform.Eda.Cli/Commands/ConfigureEda/ConfigureEdaConfig.cs
I have decided that the following areas should not be included in code coverage as it would only test our configuration or external packages which should be tested on their own.
=> #86705 - remove api consumer build code from coverage

src/CaptainHook.Api/CaptainHook.Api.csproj, src/CaptainHook.Api/Startup.cs
We decided to downgrade Swagger to v.5.5.1 because any higher version will produce a swagger document which does not work with the embedded client.
This is the relevant commit: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/9de39ba546e56668fb42733352c6d6edc6d6757d#diff-dbf89e45f47e0cf293f917f0555996db
=> #87252 Downgrade Swagger

src/CaptainHook.Api/AuthenticationDtoJsonConverter.cs, src/CaptainHook.Api/Startup.cs, src/CaptainHook.Application.Infrastructure/Mappers/DtoToEntityMapper.cs, src/CaptainHook.Application.Infrastructure/Mappers/EntityToDtoMapper.cs, src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs, src/CaptainHook.Application/Validators/Dtos/EndpointDtoValidator.cs, src/CaptainHook.Contract/NoAuthenticationDto.cs, src/CaptainHook.Storage.Cosmos/Models/EndpointSubdocument.cs, src/Tests/CaptainHook.Application.Tests/AuthenticationConfigAssertions.cs, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DeleteSubscriberRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DeleteWebhookRequestHandlerTests.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/DtoToEntityMapperTests.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/SubscriberEntityToConfigurationMapperTests/MapSubscriberAsyncTestData.cs, src/Tests/CaptainHook.Storage.Cosmos.Tests/SubscriberRepositoryTests.cs, src/Tests/CaptainHook.Tests/Director/ConfigurationMergerTests.cs, src/Tests/CaptainHook.Tests/Json/AuthenticationDtoJsonConverterTests.cs
This PR adds support for no authentication.
No authentication is serialized as null to Cosmos.
The user can send a `{ type: "None" }` authentication section trough the API or null, both will translate to no authentication.
=> #87673 Add support for no authentication

src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
There seem to be a race condition when the Director Service attempts to create more than one reader at the same time. The issue is when 2 or more reader service try to re-create the same topic and subscription at the same time, then SB gives out.
The proposed fix just swallows the exception which is only due to the race condition by assuming that the topic and subscription will be retrieved on the next step.
This does not want to be the best solution possible but at least a way to move forward at this stage. I will take the time to investigate separately a better solution to this issue.
=> #88014 Apply fix for reader crash

src/Platform.Eda.Cli/Commands/ConfigureEda/ConfigureEdaCommand.cs, src/Platform.Eda.Cli/Commands/ConfigureEda/OptionsValidation/ReplacementParamsDictionaryAttribute.cs, src/Tests/Platform.Eda.Cli.Tests/Commands/ConfigureEda/OptionsValidation/ReplacementParamsDictionaryAttributeTests.cs
There is no way to have a profit from this code currently, but as for now it can accept, validate and parse parameters from command line.
The syntax is: `configure-eda -i "C:/Temp" -p evo-host=test.eshopworld.com -p sample=value`
=> CLI accepts params replacements

src/CaptainHook.Api/Controllers/ProbeController.cs
Adding support for HEAD probes as the app is currently configured for GET probes on AFD. Will remove GET support when DevOps updates AFD configuration. Discussed with Colin in DevOps.
=> Add HEAD support to Probe

src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/PutSubscriberProcessChain.cs, src/Platform.Eda.Cli/Commands/ConfigureEda/JsonValidation/FileVariablesValidator.cs, src/Tests/Platform.Eda.Cli.Tests/Commands/ConfigureEda/JsonValidation/FileVariablesValidatorTests.cs
Recreating this PR due to merge issues.
From @tabman83
This implements a validator that validates that all the variables used by the subscriber JSON file appear in the variables declaration.
The validator has not been added to the main chain to minimize merge conflicts.
=> #88607 - validate that all used variables are defined in json file

src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/PutSubscriberProcessChain.cs, src/Platform.Eda.Cli/Commands/ConfigureEda/JsonValidation/FileReplacementsValidator.cs, src/Tests/Platform.Eda.Cli.Tests/Commands/ConfigureEda/JsonValidation/FileReplacementsValidatorTests.cs
Creating a new PR for this as I had issues with merge conflicts.
After @tabman83 
This amends the variable validator with 2 constructors:
- one will accept variables dictionary and perform the already implemented validation
- the other one will accept parameters dictionary and perform the parameters validation 
Example:
=> Task 88607 validate params for json files

src/CaptainHook.Common/Configuration/EventHandlerConfig.cs, src/CaptainHook.EventHandlerActor/Handlers/Authentication/MmAuthenticationHandler.cs, src/CaptainHook.EventHandlerActor/Handlers/GenericWebhookHandler.cs, src/CaptainHook.EventHandlerActor/Handlers/HttpSender.cs, src/CaptainHook.EventHandlerActor/Handlers/IHttpSender.cs, src/CaptainHook.EventHandlerActor/Handlers/SendRequest.cs, src/CaptainHook.EventHandlerActor/Handlers/WebhookResponseHandler.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/GenericWebhookHandlerTests.cs, src/Tests/CaptainHook.Tests/Web/WebHooks/WebhookResponseHandlerTests.cs
This PR does not enable usage of the config yet in Http Sender
=> #89814 - introduce retry-sleep-durations in webhook configuration

src/CaptainHook.EventHandlerActor/Handlers/HttpSender.cs, src/Tests/CaptainHook.EventHandlerActor.Tests/CaptainHook.EventHandlerActor.Tests.csproj, src/Tests/CaptainHook.EventHandlerActor.Tests/HttpSenderTests.cs, src/Tests/CaptainHook.EventHandlerActor.Tests/SendRequestTests.cs
With this change, the sender is going to use the config for retries instead of the hardcoded values.
Note:
The HTTP mock library does not seem to allow for subsequent requests to have different responses. If anybody knows how to enable that please let me know, I could then add an additional test which verifies that the status code changes e.g. (1) 500 (2) 200 and no (3) is required.
=> #89814 - use retry config in sender

src/CaptainHook.Application.Infrastructure/Mappers/DtoToEntityMapper.cs, src/CaptainHook.Contract/EndpointDto.cs, src/CaptainHook.Storage.Cosmos/Models/EndpointSubdocument.cs, src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/DtoToEntityMapperTests.cs
I have checked and the values are saved correctly to Cosmos. When properties are not provided they are skipped on serialisation as well.
=> #91260 - extend DTOs with Timeout and RetrySleepDurations

src/CaptainHook.DirectorService/Infrastructure/ConfigurationMerger.cs, src/Tests/CaptainHook.Tests/Director/ConfigurationMergerTests.cs
Fixes an issue while merging subscribers from KV and Cosmos where the DLQ subscriber is not recognized when already present in KV. The merger will now consider the SourceSubscriptionName in KV when present (and that's only there for DLQ subscribers) and match it with the SubscriptionName in Cosmos.
=> Fix subscribers merge issue

src/CaptainHook.Application/Validators/Dtos/WebhooksDtoValidator.cs, src/CaptainHook.EventHandlerActor/Handlers/Requests/RouteAndReplaceRequestBuilder.cs, src/CaptainHook.EventHandlerActor/Validation/WebhookRequestRuleForRouteAndReplaceValidator.cs, src/Tests/CaptainHook.Application.Tests/RequestValidators/UpsertSubscriberRequestValidatorTests.cs, src/Tests/CaptainHook.EventHandlerActor.Tests/Validation/WebhookRequestRuleForRouteAndReplaceValidatorTests.cs
We are introducing a change with this PR which will:
1. stop requiring exactly one default selector * in RouteAndReplace
1. send a UnroutableEvent to AI if a message comes in which doesn't match the configuration (and we don't have * to fall back)
=> #91761 - allow routes not to specify default selector

src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs, src/CaptainHook.Application/Handlers/Subscribers/UpsertSubscriberRequestHandler.cs, src/CaptainHook.Application/Validators/Dtos/SubscriberDtoValidator.cs, src/CaptainHook.Contract/SubscriberDto.cs, src/CaptainHook.Domain/Entities/SubscriberEntity.cs, src/CaptainHook.Domain/Entities/WebhooksEntity.cs, src/CaptainHook.Storage.Cosmos/Models/SubscriberDocument.cs, src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs, src/Tests/CaptainHook.Application.Tests/Infrastructure/SubscriberEntityToConfigurationMapperTests/WebhookAndCallbacksMapSubscriberAsyncTests.cs, src/Tests/CaptainHook.Application.Tests/RequestValidators/UpsertSubscriberRequestValidatorTests.cs, src/Tests/CaptainHook.Tests/Services/Reliable/EventReaderInitDataTests.cs, src/Tests/CaptainHook.TestsInfrastructure/Builders/SubscriberBuilder.cs
I have tested the following scenarios:
- new subscriber added via API with no MaxDeliveryCount (default 10 used)
- new subscriber added via API with valid and invalid MaxDeliveryCount
- subscriber updated via API with MaxDeliveryCount
- subscriber updated via API with no MaxDeliveryCount
- manual change in CosmosDB and restart of CH results in proper values in SB
- regular KV entries with no MaxDeliveryCount result in default 10
For each of the above, I have tested that the subscriber in SB is refreshed with the relevant MaxDeliveryCount value.
=> #91261 #91264 Extend subscriber with MaxDeliveryCount functionality

src/CaptainHook.Common/Telemetry/FailedWebhookExceptionEvent.cs, src/CaptainHook.EventHandlerActor/Handlers/GenericWebhookHandler.cs
Now exception details as well as the invoked uri are logged in `FailedWebhookExceptionEvent`
=> New event and logging
